// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/hil_gps/hil_gps.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class HilGpsImpl;

/**
 * @brief 
 */
class HilGps : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto hil_gps = HilGps(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit HilGps(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto hil_gps = HilGps(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit HilGps(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~HilGps() override;





    /**
     * @brief 
     */
    struct HilGpsInfo {
        
        uint64_t time_usec{}; /**< @brief */
        uint32_t fix_type{}; /**< @brief */
        int32_t lat{}; /**< @brief */
        int32_t lon{}; /**< @brief */
        int32_t alt{}; /**< @brief */
        uint32_t eph{}; /**< @brief */
        uint32_t epv{}; /**< @brief */
        uint32_t vel{}; /**< @brief */
        int32_t vn{}; /**< @brief */
        int32_t ve{}; /**< @brief */
        int32_t vd{}; /**< @brief */
        uint32_t cog{}; /**< @brief */
        uint32_t satellites_visible{}; /**< @brief */
        uint32_t id{}; /**< @brief */
        uint32_t yaw{}; /**< @brief */
    };

    /**
     * @brief Equal operator to compare two `HilGps::HilGpsInfo` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const HilGps::HilGpsInfo& lhs, const HilGps::HilGpsInfo& rhs);

    /**
     * @brief Stream operator to print information about a `HilGps::HilGpsInfo`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, HilGps::HilGpsInfo const& hil_gps_info);





    /**
     * @brief Possible results returned for mocap requests
     */
    enum class Result {
        Unknown, /**< @brief Unknown error. */
        Success, /**< @brief Request succeeded. */
        NoSystem, /**< @brief No system is connected. */
        ConnectionError, /**< @brief Connection error. */
        InvalidRequestData, /**< @brief Invalid request data. */
        Unsupported, /**< @brief Function unsupported. */
    };

    /**
     * @brief Stream operator to print information about a `HilGps::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, HilGps::Result const& result);



    /**
     * @brief Callback type for asynchronous HilGps calls.
     */
    using ResultCallback = std::function<void(Result)>;






    /**
     * @brief Send HIL GPS information
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    Result set_hil_gps(HilGpsInfo hil_gps_info) const;




    /**
     * @brief Copy constructor.
     */
    HilGps(const HilGps& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const HilGps& operator=(const HilGps&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<HilGpsImpl> _impl;
};

} // namespace mavsdk