// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/hil_gps/hil_gps.proto)

#include <iomanip>

#include "hil_gps_impl.h"
#include "plugins/hil_gps/hil_gps.h"

namespace mavsdk {

using HilGpsInfo = HilGps::HilGpsInfo;




HilGps::HilGps(System& system) : PluginBase(), _impl{std::make_unique<HilGpsImpl>(system)} {}

HilGps::HilGps(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<HilGpsImpl>(system)} {}


HilGps::~HilGps() {}





HilGps::Result HilGps::set_hil_gps(HilGpsInfo hil_gps_info) const
{
    return _impl->set_hil_gps(hil_gps_info);
}



bool operator==(const HilGps::HilGpsInfo& lhs, const HilGps::HilGpsInfo& rhs)
{
    return
        (rhs.time_usec == lhs.time_usec) &&
        (rhs.fix_type == lhs.fix_type) &&
        (rhs.lat == lhs.lat) &&
        (rhs.lon == lhs.lon) &&
        (rhs.alt == lhs.alt) &&
        (rhs.eph == lhs.eph) &&
        (rhs.epv == lhs.epv) &&
        (rhs.vel == lhs.vel) &&
        (rhs.vn == lhs.vn) &&
        (rhs.ve == lhs.ve) &&
        (rhs.vd == lhs.vd) &&
        (rhs.cog == lhs.cog) &&
        (rhs.satellites_visible == lhs.satellites_visible) &&
        (rhs.id == lhs.id) &&
        (rhs.yaw == lhs.yaw);
}

std::ostream& operator<<(std::ostream& str, HilGps::HilGpsInfo const& hil_gps_info)
{
    str << std::setprecision(15);
    str << "hil_gps_info:" << '\n'
        << "{\n";
    str << "    time_usec: " << hil_gps_info.time_usec << '\n';
    str << "    fix_type: " << hil_gps_info.fix_type << '\n';
    str << "    lat: " << hil_gps_info.lat << '\n';
    str << "    lon: " << hil_gps_info.lon << '\n';
    str << "    alt: " << hil_gps_info.alt << '\n';
    str << "    eph: " << hil_gps_info.eph << '\n';
    str << "    epv: " << hil_gps_info.epv << '\n';
    str << "    vel: " << hil_gps_info.vel << '\n';
    str << "    vn: " << hil_gps_info.vn << '\n';
    str << "    ve: " << hil_gps_info.ve << '\n';
    str << "    vd: " << hil_gps_info.vd << '\n';
    str << "    cog: " << hil_gps_info.cog << '\n';
    str << "    satellites_visible: " << hil_gps_info.satellites_visible << '\n';
    str << "    id: " << hil_gps_info.id << '\n';
    str << "    yaw: " << hil_gps_info.yaw << '\n';
    str << '}';
    return str;
}



std::ostream& operator<<(std::ostream& str, HilGps::Result const& result)
{
    switch (result) {
        case HilGps::Result::Unknown:
            return str << "Unknown";
        case HilGps::Result::Success:
            return str << "Success";
        case HilGps::Result::NoSystem:
            return str << "No System";
        case HilGps::Result::ConnectionError:
            return str << "Connection Error";
        case HilGps::Result::InvalidRequestData:
            return str << "Invalid Request Data";
        case HilGps::Result::Unsupported:
            return str << "Unsupported";
        default:
            return str << "Unknown";
    }
}




} // namespace mavsdk