// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/hil_gps/hil_gps.proto)

#include "hil_gps/hil_gps.grpc.pb.h"
#include "plugins/hil_gps/hil_gps.h"

#include "mavsdk.h"

#include "lazy_plugin.h"

#include "log.h"
#include <atomic>
#include <cmath>
#include <future>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <vector>

namespace mavsdk {
namespace mavsdk_server {


template<typename HilGps = HilGps, typename LazyPlugin = LazyPlugin<HilGps>>

class HilGpsServiceImpl final : public rpc::hil_gps::HilGpsService::Service {
public:

    HilGpsServiceImpl(LazyPlugin& lazy_plugin) : _lazy_plugin(lazy_plugin) {}



    template<typename ResponseType>
    void fillResponseWithResult(ResponseType* response, mavsdk::HilGps::Result& result) const
    {
        auto rpc_result = translateToRpcResult(result);

        auto* rpc_hil_gps_result = new rpc::hil_gps::HilGpsResult();
        rpc_hil_gps_result->set_result(rpc_result);
        std::stringstream ss;
        ss << result;
        rpc_hil_gps_result->set_result_str(ss.str());

        response->set_allocated_hil_gps_result(rpc_hil_gps_result);
    }




    static std::unique_ptr<rpc::hil_gps::HilGpsInfo> translateToRpcHilGpsInfo(const mavsdk::HilGps::HilGpsInfo &hil_gps_info)
    {
        auto rpc_obj = std::make_unique<rpc::hil_gps::HilGpsInfo>();


            
        rpc_obj->set_time_usec(hil_gps_info.time_usec);
            
        
            
        rpc_obj->set_fix_type(hil_gps_info.fix_type);
            
        
            
        rpc_obj->set_lat(hil_gps_info.lat);
            
        
            
        rpc_obj->set_lon(hil_gps_info.lon);
            
        
            
        rpc_obj->set_alt(hil_gps_info.alt);
            
        
            
        rpc_obj->set_eph(hil_gps_info.eph);
            
        
            
        rpc_obj->set_epv(hil_gps_info.epv);
            
        
            
        rpc_obj->set_vel(hil_gps_info.vel);
            
        
            
        rpc_obj->set_vn(hil_gps_info.vn);
            
        
            
        rpc_obj->set_ve(hil_gps_info.ve);
            
        
            
        rpc_obj->set_vd(hil_gps_info.vd);
            
        
            
        rpc_obj->set_cog(hil_gps_info.cog);
            
        
            
        rpc_obj->set_satellites_visible(hil_gps_info.satellites_visible);
            
        
            
        rpc_obj->set_id(hil_gps_info.id);
            
        
            
        rpc_obj->set_yaw(hil_gps_info.yaw);
            
        

        return rpc_obj;
    }

    static mavsdk::HilGps::HilGpsInfo translateFromRpcHilGpsInfo(const rpc::hil_gps::HilGpsInfo& hil_gps_info)
    {
        mavsdk::HilGps::HilGpsInfo obj;


            
        obj.time_usec = hil_gps_info.time_usec();
            
        
            
        obj.fix_type = hil_gps_info.fix_type();
            
        
            
        obj.lat = hil_gps_info.lat();
            
        
            
        obj.lon = hil_gps_info.lon();
            
        
            
        obj.alt = hil_gps_info.alt();
            
        
            
        obj.eph = hil_gps_info.eph();
            
        
            
        obj.epv = hil_gps_info.epv();
            
        
            
        obj.vel = hil_gps_info.vel();
            
        
            
        obj.vn = hil_gps_info.vn();
            
        
            
        obj.ve = hil_gps_info.ve();
            
        
            
        obj.vd = hil_gps_info.vd();
            
        
            
        obj.cog = hil_gps_info.cog();
            
        
            
        obj.satellites_visible = hil_gps_info.satellites_visible();
            
        
            
        obj.id = hil_gps_info.id();
            
        
            
        obj.yaw = hil_gps_info.yaw();
            
        
        return obj;
    }




    static rpc::hil_gps::HilGpsResult::Result translateToRpcResult(const mavsdk::HilGps::Result& result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case mavsdk::HilGps::Result::Unknown:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_UNKNOWN;
            case mavsdk::HilGps::Result::Success:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_SUCCESS;
            case mavsdk::HilGps::Result::NoSystem:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_NO_SYSTEM;
            case mavsdk::HilGps::Result::ConnectionError:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_CONNECTION_ERROR;
            case mavsdk::HilGps::Result::InvalidRequestData:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_INVALID_REQUEST_DATA;
            case mavsdk::HilGps::Result::Unsupported:
                return rpc::hil_gps::HilGpsResult_Result_RESULT_UNSUPPORTED;
        }
    }

    static mavsdk::HilGps::Result translateFromRpcResult(const rpc::hil_gps::HilGpsResult::Result result)
    {
        switch (result) {
            default:
                LogErr() << "Unknown result enum value: " << static_cast<int>(result);
            // FALLTHROUGH
            case rpc::hil_gps::HilGpsResult_Result_RESULT_UNKNOWN:
                return mavsdk::HilGps::Result::Unknown;
            case rpc::hil_gps::HilGpsResult_Result_RESULT_SUCCESS:
                return mavsdk::HilGps::Result::Success;
            case rpc::hil_gps::HilGpsResult_Result_RESULT_NO_SYSTEM:
                return mavsdk::HilGps::Result::NoSystem;
            case rpc::hil_gps::HilGpsResult_Result_RESULT_CONNECTION_ERROR:
                return mavsdk::HilGps::Result::ConnectionError;
            case rpc::hil_gps::HilGpsResult_Result_RESULT_INVALID_REQUEST_DATA:
                return mavsdk::HilGps::Result::InvalidRequestData;
            case rpc::hil_gps::HilGpsResult_Result_RESULT_UNSUPPORTED:
                return mavsdk::HilGps::Result::Unsupported;
        }
    }




    grpc::Status SetHilGps(
        grpc::ServerContext* /* context */,
        const rpc::hil_gps::SetHilGpsRequest* request,
        rpc::hil_gps::SetHilGpsResponse* response) override
    {
        if (_lazy_plugin.maybe_plugin() == nullptr) {
            
            if (response != nullptr) {
                auto result = mavsdk::HilGps::Result::NoSystem;
                fillResponseWithResult(response, result);
            }
            
            return grpc::Status::OK;
        }

        if (request == nullptr) {
            LogWarn() << "SetHilGps sent with a null request! Ignoring...";
            return grpc::Status::OK;
        }
            
        
        auto result = _lazy_plugin.maybe_plugin()->set_hil_gps(translateFromRpcHilGpsInfo(request->hil_gps_info()));
        

        
        if (response != nullptr) {
            fillResponseWithResult(response, result);
        }
        

        return grpc::Status::OK;
    }


    void stop() {
        _stopped.store(true);
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto& prom : _stream_stop_promises) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        }
    }

private:
    void register_stream_stop_promise(std::weak_ptr<std::promise<void>> prom) {
        // If we have already stopped, set promise immediately and don't add it to list.
        if (_stopped.load()) {
            if (auto handle = prom.lock()) {
                handle->set_value();
            }
        } else {
            std::lock_guard<std::mutex> lock(_stream_stop_mutex);
            _stream_stop_promises.push_back(prom);
        }
    }

    void unregister_stream_stop_promise(std::shared_ptr<std::promise<void>> prom) {
        std::lock_guard<std::mutex> lock(_stream_stop_mutex);
        for (auto it = _stream_stop_promises.begin(); it != _stream_stop_promises.end(); /* ++it */) {
            if (it->lock() == prom) {
                it = _stream_stop_promises.erase(it);
            } else {
                ++it;
            }
        }
    }


    LazyPlugin& _lazy_plugin;

    std::atomic<bool> _stopped{false};
    std::mutex _stream_stop_mutex{};
    std::vector<std::weak_ptr<std::promise<void>>> _stream_stop_promises {};
};

} // namespace mavsdk_server
} // namespace mavsdk